ktor:
  deployment:
    port: "$PORT:8080"
    host: 0.0.0.0
  application:
    modules:
      - com.example.ApplicationKt.module

database:
  url: "jdbc:postgresql://localhost:5432/icu_db"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "2025"

jwt:
  audience: "http://yamabiko.proxy.rlwy/"
  domain: "http://yamabiko.proxy.rlwy/"
  realm: "Access to protected routes"
  secret: "secret"

postgres:
  url: "jdbc:postgresql://localhost:5432/icu_db"
  user: postgres
  password: 2025
